name: Build, Test & Deploy → Vercel

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run tests
      - name: Run tests
        run: |
          if [ -f package.json ] && grep -q "\"test\":" package.json; then
            npm test
          else
            echo "No tests defined."
          fi

      # 5️⃣ Build project
      - name: Build project
        run: |
          if [ -f package.json ] && grep -q "\"build\":" package.json; then
            npm run build
          else
            echo "No build script defined."
          fi

     # 6️⃣ Deploy to Vercel
      - name: Deploy to Vercel (production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel deploy --prod --confirm --token "$VERCEL_TOKEN"
